import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TodoProvider from "./_contexts/TodoContext";
import { ThemeProvider } from "./_components/DarkMode";
import { Children } from "react";
import ApolloProviders from "./_contexts/ApolloProvider";
import DeletedTodoProvider from "./_contexts/DeletedTodoContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const client = new ApolloClient({
//   uri: "http://localhost:8080/api/graphql",
// });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TodoProvider>
              <DeletedTodoProvider>{children}</DeletedTodoProvider>
              {/* <TokenProvider>{children}</TokenProvider> */}
            </TodoProvider>
          </ThemeProvider>
        </ApolloProviders>
      </body>
    </html>
  );
}
